// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
)

type TodoItem struct {
	ID          string       `json:"id"`
	Description string       `json:"description"`
	Complete    bool         `json:"complete"`
	CreatedAt   sql.NullTime `json:"created_at"`
	CompletedAt interface{}  `json:"completed_at"`
}
