// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CompleteTodo(ctx context.Context, id string) error
	GetTodo(ctx context.Context, id string) (*TodoItem, error)
	InsertTodo(ctx context.Context, arg *InsertTodoParams) error
	ListTodos(ctx context.Context) ([]*TodoItem, error)
}

var _ Querier = (*Queries)(nil)
