// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CompleteTodo(ctx context.Context, id string) error
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	DeleteUser(ctx context.Context, id string) error
	GetTodo(ctx context.Context, id string) (*TodoItem, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id string) (*User, error)
	InsertTodo(ctx context.Context, arg *InsertTodoParams) error
	IsUserValidated(ctx context.Context, id string) (int64, error)
	ListTodos(ctx context.Context, userID string) ([]*TodoItem, error)
	UpdateUserPassword(ctx context.Context, arg *UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
